#!/bin/bash

#SBATCH --job-name=mytestjob
#SBATCH --ntasks-per-node=1
#SBATCH --mem=1G
#SBATCH --time=06:00:00

module load singularitypro
#parse config.json for input parameters (here, we are pulling "t1")
data=$(jq -r .set config-dataqual.json)
singularity exec -e docker://dtyoung/eeglab-pipeline:eeglab octave-cli ./bids_dataqual.m $data
